name: BAMradio
main: yt.bam.bamradio.BAMradio
version: 1.6
description: Plays midi files.
softdepend: [NoteBlockAPI,WorldGuard]
commands:
  bamradio:
    description: Show all BAMradio commands
    usage: /bamradio
  br:
    description: Alias to /bamradio
    usage: /br